repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.rs$'
      - id: end-of-file-fixer
        exclude: '\.rs$'
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt # Runs cargo fmt
      - id: clippy # Runs cargo clippy (Linter)
      - id: cargo-check # Checks if the project compiles (fast)
